"use client";
import { useState, type FormEvent, type ReactNode } from "react";
import Link from "next/link";
import { LayoutDashboard, CalendarDays, Users, ScanLine, Flag, Trophy, BarChart3, Megaphone, ShieldCheck, Settings, History, Plus, ArrowUpRight, Download, Save, ArrowLeft, RefreshCw, CheckCircle2 } from "lucide-react";
import { Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarGroup,SidebarGroupLabel,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarFooter,SidebarInset,SidebarTrigger } from "@/components/ui/sidebar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { NativeSelect,NativeSelectOption } from "@/components/ui/native-select";
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from "@/components/ui/alert-dialog";
import { Switch } from "@/components/ui/switch";
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";
import { Heading,Empty,DataTable,LoadState,Pick,Pill,SearchBox,Metric,useHub,date,time,labels,type Row } from "@/components/hub-shared";
import { FieldPages } from "@/components/field-pages";
const navigation=[["","Tổng quan",LayoutDashboard],["su-kien","Sự kiện",CalendarDays],["sinh-vien","Người tham dự",Users],["check-in","Check-in",ScanLine],["doi","Đội tham gia",Users],["tram","Trạm thử thách",Flag],["dieu-phoi","Điều phối K26",Flag],["mat-thu","Kho mật thư",ShieldCheck],["thoi-gian","Kết quả trạm",History],["khieu-chien","Khiêu chiến & giải cuối",Trophy],["kich-ban","Kịch bản & ý tưởng",CalendarDays],["cham-diem","Chấm điểm chung",Trophy],["bao-cao","Báo cáo",BarChart3],["thong-bao","Thông báo",Megaphone],["phan-quyen","Thành viên & quyền",ShieldCheck],["nhat-ky","Nhật ký hoạt động",History],["cai-dat","Cài đặt",Settings]] as const;
export function AdminPages({path=[],name,role}:{path?:string[];name:string;role:string}){
 const {data,error,loading,reload}=useHub("/api/hub/admin");const route=path[0]||"";const[filter,setFilter]=useState("");const[search,setSearch]=useState("");const[modal,setModal]=useState<Row|null>(null);const[busy,setBusy]=useState(false);const[formError,setFormError]=useState("");const[cancel,setCancel]=useState<Row|null>(null);const[reason,setReason]=useState("");
 const manager=["OWNER","ADMIN"].includes(role);
 const events:Row[]=data?.events||[];const registrations:Row[]=(data?.registrations||[]).filter((r:Row)=>(!filter||r.event_id===filter)&&(!search||(r.full_name+" "+r.student_id+" "+r.class_name+" "+r.ticket_code).toLowerCase().includes(search.toLowerCase())));
 const eventRows=events.filter(e=>!filter||e.id===filter);const teams:Row[]=(data?.teams||[]).filter((t:Row)=>!filter||t.event_id===filter);const stations:Row[]=(data?.stations||[]).filter((t:Row)=>!filter||t.event_id===filter);
 async function mutate(action:string,payload:Row,close=true){setBusy(true);setFormError("");try{const r=await fetch("/api/hub/"+action,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json() as Row;if(!r.ok)throw new Error(d.message);toast.success(d.message);await reload();if(close)setModal(null);return true;}catch(e){const s=e instanceof Error?e.message:"Chưa thể lưu.";setFormError(s);toast.error(s);return false;}finally{setBusy(false);}}
 function open(kind:string,item:Row={}){setFormError("");setModal({kind,...item});}
 const title=navigation.find(n=>n[0]===route)?.[1]||"Quản lý sự kiện";
 const navVisible=navigation.filter(([r])=>manager||["","su-kien","check-in","doi","tram","cham-diem","bao-cao","thong-bao","cai-dat"].includes(r));
 return <SidebarProvider><Sidebar className="event-sidebar"><SidebarHeader><Link href="/admin" className="brand"><b>KT<span>✦</span></b><div>CNKT <strong>EVENTS</strong><small>KHÔNG GIAN BAN TỔ CHỨC</small></div></Link></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>ĐIỀU HÀNH SỰ KIỆN</SidebarGroupLabel><SidebarMenu>{navVisible.map(([href,text,Icon])=><SidebarMenuItem key={href}><SidebarMenuButton asChild isActive={route===href}><Link href={"/admin"+(href?"/"+href:"")}><Icon/><span>{text}</span></Link></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup></SidebarContent><SidebarFooter><Link href="/" className="portal-link">Cổng sinh viên<ArrowUpRight size={17}/></Link><div className="operator-card"><div className="avatar">{name.slice(0,1)}</div><div><strong>{name}</strong><small>{labels[role]}</small></div></div></SidebarFooter></Sidebar><SidebarInset className="admin-inset"><header className="admin-top"><div><SidebarTrigger/><span>Không gian BTC <span className="muted">/ {title}</span></span></div><Button variant="ghost" size="sm" onClick={reload}><RefreshCw/>Làm mới</Button></header><main className="admin-main"><Heading eyebrow="CNKT / DTHU / 2026" title={route==="su-kien"&&path[1]?"Thiết lập sự kiện":title} text={route===""?"Tình hình đăng ký và vận hành các chương trình của Khoa.":undefined}>{manager&&route==="su-kien"&&!path[1]&&<Button asChild><Link href="/admin/su-kien/tao-moi"><Plus/>Tạo sự kiện</Link></Button>}{manager&&["doi","tram","thong-bao","phan-quyen"].includes(route)&&<Button onClick={()=>open(route)}><Plus/>{route==="doi"?"Thêm đội":route==="tram"?"Thêm trạm":route==="thong-bao"?"Soạn thông báo":"Thêm thành viên"}</Button>}</Heading><LoadState {...{error,loading,reload}}/>
 {data&&<>
 {['dieu-phoi','mat-thu','thoi-gian','khieu-chien','kich-ban'].includes(route)&&<FieldPages route={route} manager={manager}/>}
 {!events.length&&manager&&<div className="setup-banner"><div><strong>Khởi tạo chương trình K26</strong><p>Thêm Teambuilding 105 suất, Gala K26 và 8 trạm. Không ghi đè dữ liệu đã có.</p></div><Button disabled={busy} onClick={()=>mutate("initialize",{})}>Khởi tạo K26</Button></div>}
 {route===""&&<><div className="metric-grid"><Metric label="Sự kiện" value={events.length} caption={events.filter(e=>e.registration_open).length+" sự kiện mở đăng ký"}/><Metric label="Lượt đăng ký hợp lệ" value={events.reduce((n,e)=>n+e.registered,0)} caption="Không gồm vé đã hủy"/><Metric label="Đã check-in" value={events.reduce((n,e)=>n+e.checked_in,0)} caption="Mỗi vé ghi nhận một lần"/><Metric label="Trạm thử thách" value={data.stations.length} caption={data.teams.length+" đội đã được tạo"}/></div><div className="admin-split"><section className="panel"><div className="section-head"><h2>Sự kiện đang theo dõi</h2><Link href="/admin/su-kien">Xem tất cả →</Link></div>{events.map(e=><Link href={"/admin/su-kien/"+e.id} className="event-line" key={e.id}><div className="mini-date">{e.event_date?e.event_date.slice(8):"—"}<small>{e.event_date?"TH"+e.event_date.slice(5,7):"CHỜ"}</small></div><div><strong>{e.title}</strong><p>{date(e.event_date)} · {e.venue}</p><div className="capacity-track"><span style={{width:e.capacity?Math.min(100,e.registered/e.capacity*100)+"%":"0%"}}/></div><small>{e.registered} đăng ký {e.capacity?" / "+e.capacity+" suất":""}</small></div><Pill value={e.status}/></Link>)}{!events.length&&<Empty/>}</section><section className="panel navy-panel"><span className="eyebrow">SẴN SÀNG VẬN HÀNH</span><h2>Một chương trình.<br/>Một luồng liền mạch.</h2><ol><li>Chốt thông tin & mở đăng ký</li><li>Đối soát danh sách & phân đội</li><li>Check-in & chấm điểm các trạm</li><li>Tổng kết & xuất báo cáo</li></ol><Button variant="secondary" asChild><Link href="/admin/check-in">Mở cổng check-in<ArrowRightIcon/></Link></Button></section></div><section className="panel"><h2>Hoạt động gần đây</h2>{data.audit.slice(0,5).map((a:Row)=><div className="audit-line" key={a.id}><CheckCircle2 size={17}/><div><strong>{a.detail}</strong><p>{time(a.created_at)} · {a.operator}</p></div></div>)}{!data.audit.length&&<p className="muted">Chưa có hoạt động được ghi nhận.</p>}</section></>}
 {route==="su-kien"&&!path[1]&&<DataTable headers={["Tên sự kiện","Thời gian","Đăng ký","Check-in","Trạng thái",""]} rows={events.map(e=>[<strong>{e.title}<small className="cell-sub">{e.audience}</small></strong>,date(e.event_date),e.registered+" / "+(e.capacity||"∞"),e.checked_in,<Pill value={e.status}/>,<Button asChild variant="outline" size="sm"><Link href={"/admin/su-kien/"+e.id}>{manager?"Chỉnh sửa":"Xem"}</Link></Button>])}/>}
 {route==="su-kien"&&path[1]&&(manager?<EventEditor key={path[1]} event={events.find(e=>e.id===path[1])} isNew={path[1]==="tao-moi"} busy={busy} error={formError} save={b=>mutate("events",b,false)}/>:<Empty title="Chỉ quản lý được chỉnh sửa sự kiện"/>)}
 {["sinh-vien","doi","tram","cham-diem","bao-cao"].includes(route)&&<div className="toolbar"><Pick value={filter} onChange={setFilter} options={events} all/>{route==="sinh-vien"&&<SearchBox value={search} onChange={setSearch} placeholder="Tìm MSSV, họ tên, lớp hoặc mã vé..."/>}{manager&&["sinh-vien","bao-cao"].includes(route)&&<Button asChild variant="outline"><a href={"/api/admin/export"+(filter?"?event="+encodeURIComponent(filter):"")}><Download/>Xuất danh sách CSV</a></Button>}</div>}
 {route==="sinh-vien"&&(manager?<><p className="table-caption">{registrations.length} kết quả · tối đa 5.000 dòng trên màn hình; file xuất chứa toàn bộ danh sách.</p><DataTable headers={["Sinh viên","Sự kiện / lớp","Trạng thái","Đội","Đăng ký lúc",""]} rows={registrations.map(r=>[<strong>{r.full_name}<small className="cell-sub">{r.student_id}</small></strong>,<span>{r.event_title}<small className="cell-sub">{r.class_name}</small></span>,r.checked_in_at?<Pill value="Đã check-in"/>:<Pill value={r.status}/>,<NativeSelect aria-label={"Đội của "+r.full_name} value={r.team_id||""} disabled={busy||r.status==="CANCELLED"} onChange={e=>mutate("assign",{registration_id:r.id,team_id:e.target.value||null})}><NativeSelectOption value="">Chưa phân đội</NativeSelectOption>{data.teams.filter((t:Row)=>t.event_id===r.event_id).map((t:Row)=><NativeSelectOption key={t.id} value={t.id}>{t.name}</NativeSelectOption>)}</NativeSelect>,time(r.created_at),<div className="row-actions"><Button variant="outline" size="sm" onClick={()=>open("participant",r)}>Chi tiết</Button>{!r.checked_in_at&&r.status!=="CANCELLED"&&<Button variant="ghost" size="sm" onClick={()=>{setCancel(r);setReason("");}}>Hủy vé</Button>}</div>])}/></>:<Empty title="Không có quyền xem dữ liệu cá nhân"/>)}
 {route==="check-in"&&<Checkin events={events} busy={busy} allowed={manager||role==="CHECKIN"} save={b=>mutate("checkin",b,false)}/>}
 {route==="doi"&&<><div className="compact-grid">{teams.map(t=><section className="panel team-panel" key={t.id}><div className="team-initial">{t.name.slice(0,2).toUpperCase()}</div><h2>{t.name}</h2><p>{events.find(e=>e.id===t.event_id)?.title}</p><strong className="team-count">{t.members}<small> thành viên</small></strong><Link href="/admin/sinh-vien">Phân sinh viên vào đội →</Link></section>)}</div>{!teams.length&&<Empty title="Chưa có đội" text="Tạo đội theo sự kiện, sau đó phân thành viên tại trang Người tham dự."/>}</>}
 {route==="tram"&&<><div className="compact-grid">{stations.map(s=><section className="panel" key={s.id}><span className="eyebrow">TRẠM {String(s.station_number).padStart(2,"0")}</span><h2>{s.title}</h2><p>{s.description}</p><small className="cell-sub">{events.find(e=>e.id===s.event_id)?.title}</small>{manager&&<Button variant="outline" onClick={()=>open("tram",s)}>Chỉnh sửa trạm</Button>}</section>)}</div>{!stations.length&&<Empty title="Chưa có trạm" text="Khởi tạo K26 để thêm 8 trạm Teambuilding hoặc tạo trạm mới."/>}</>}
 {route==="cham-diem"&&<><section className="panel"><h2>Điểm theo đội & trạm</h2><p>Điểm mỗi trạm: 0–100. Lưu lại cùng đội/trạm sẽ cập nhật kết quả cũ; mọi lần sửa đều được ghi nhật ký.</p>{(manager||role==="STATION")&&<Button onClick={()=>open("score")}><Plus/>Ghi nhận điểm</Button>}</section><DataTable headers={["Đội","Sự kiện","Trạm đã chấm","Tổng điểm"]} rows={[...teams].map((t):Row=>({...t,points:data.scores.filter((s:Row)=>s.team_id===t.id).reduce((a:number,s:Row)=>a+s.points,0),count:data.scores.filter((s:Row)=>s.team_id===t.id).length})).sort((a,b)=>b.points-a.points).map(t=>[t.name,events.find(e=>e.id===t.event_id)?.short_title,t.count,<strong>{t.points}</strong>])}/><section className="panel"><h2>Chi tiết điểm đã ghi</h2><DataTable headers={["Đội","Trạm","Điểm","Ghi chú","Lần cập nhật",""]} rows={data.scores.filter((s:Row)=>teams.some(t=>t.id===s.team_id)).map((s:Row)=>[data.teams.find((t:Row)=>t.id===s.team_id)?.name,data.stations.find((t:Row)=>t.id===s.station_id)?.title,s.points,s.note,time(s.updated_at),(manager||role==="STATION")?<Button size="sm" variant="outline" onClick={()=>open("score",s)}>Sửa điểm</Button>:null])}/></section></>}
 {route==="bao-cao"&&<><div className="metric-grid"><Metric label="Lượt giữ chỗ hợp lệ" value={eventRows.reduce((a,e)=>a+e.registered,0)}/><Metric label="Lượt check-in" value={eventRows.reduce((a,e)=>a+e.checked_in,0)}/><Metric label="Tỷ lệ có mặt" value={(eventRows.reduce((a,e)=>a+e.registered,0)?Math.round(eventRows.reduce((a,e)=>a+e.checked_in,0)/eventRows.reduce((a,e)=>a+e.registered,0)*100):0)+"%"}/><Metric label="Chưa check-in" value={eventRows.reduce((a,e)=>a+e.registered-e.checked_in,0)}/></div><section className="panel"><h2>Đăng ký & có mặt theo sự kiện</h2><p className="muted">Chỉ tính vé không bị hủy. Tỷ lệ có mặt = check-in / đăng ký hợp lệ.</p><DataTable headers={["Sự kiện","Đăng ký","Check-in","Chưa check-in","Tỷ lệ"]} rows={eventRows.map(e=>[e.title,e.registered,e.checked_in,e.registered-e.checked_in,(e.registered?Math.round(e.checked_in/e.registered*100):0)+"%"])}/></section><p className="muted">Không bao gồm danh sách website cũ khi chưa được nhập và đối soát. Các chỉ số không phải số liệu minh họa.</p></>}
 {route==="thong-bao"&&<><div className="notice-grid">{data.notices.map((n:Row)=><section className="panel" key={n.id}><Pill value={n.published?"Đã công bố":"Bản nháp"}/><h2>{n.title}</h2><p className="prose-text">{n.body}</p><small className="cell-sub">{time(n.created_at)} · {events.find(e=>e.id===n.event_id)?.title||"Toàn khoa"}</small>{manager&&<Button variant="outline" onClick={()=>open("thong-bao",n)}>Chỉnh sửa</Button>}</section>)}</div>{!data.notices.length&&<Empty title="Chưa có thông báo" text="Soạn thông báo và bật Công bố để hiển thị ở cổng sinh viên. Không tự gửi email hoặc tin nhắn."/>}</>}
 {route==="phan-quyen"&&(role==="OWNER"?<><div className="info-banner">Phân quyền trong ứng dụng không tự chia sẻ quyền truy cập website. Thành viên vẫn cần được chủ sở hữu cho phép truy cập Site.</div><DataTable headers={["Họ tên","Email","Vai trò",""]} rows={data.members.map((m:Row)=>[m.name,m.email,<Pill value={m.role}/>,<Button variant="outline" onClick={()=>open("phan-quyen",m)}>Sửa quyền</Button>])}/><section className="panel"><h2>Phạm vi từng vai trò</h2><DataTable headers={["Vai trò","Quyền thao tác"]} rows={[["Chủ sở hữu","Toàn bộ; thêm và thu hồi quyền thành viên"],["Quản lý","Sự kiện, danh sách, phân đội, check-in, điểm, báo cáo, thông báo"],["Check-in","Xem tổng quan; check-in theo đúng sự kiện"],["Trọng tài","Xem đội, trạm; ghi và sửa điểm"],["Xem tổng quan","Chỉ đọc; không xem danh sách dữ liệu cá nhân"]]}/></section></>:<Empty title="Chỉ chủ sở hữu được thay đổi quyền thành viên"/>)}
 {route==="nhat-ky"&&(manager?<><p className="muted">100 hoạt động gần nhất. Nhật ký giữ người thao tác, thời điểm và nội dung thay đổi.</p><DataTable headers={["Thời điểm","Người thực hiện","Nghiệp vụ","Chi tiết"]} rows={data.audit.map((a:Row)=>[time(a.created_at),a.operator,a.action,a.detail])}/></>:<Empty title="Không có quyền xem nhật ký"/>)}
 {route==="cai-dat"&&<div className="admin-split"><section className="panel"><h2>Thông tin hệ thống</h2><dl className="settings-list"><dt>Đơn vị</dt><dd>Khoa Công nghệ và Kỹ thuật</dd><dt>Trường</dt><dd>Trường Đại học Đồng Tháp</dd><dt>Múi giờ</dt><dd>Việt Nam · UTC+7</dd><dt>Nhận vé</dt><dd>Hiển thị trực tiếp, tra cứu bằng mã, in từ trình duyệt</dd><dt>Email tự động</dt><dd>Chưa kết nối dịch vụ gửi email</dd><dt>Kiểm tra MSSV</dt><dd>6–12 chữ số; chưa đối chiếu danh sách sinh viên chính thức</dd></dl></section><section className="panel"><h2>Quy tắc dữ liệu</h2><ul className="check-list"><li>Mỗi MSSV chỉ một đăng ký cho từng sự kiện.</li><li>Giới hạn suất được kiểm tra tại thời điểm lưu.</li><li>Check-in một lần cho mỗi vé.</li><li>Đội, trạm và sinh viên được đối chiếu cùng sự kiện.</li><li>Vé bị hủy không tính vào tổng đăng ký hợp lệ.</li><li>Bằng điểm xếp đồng hạng.</li></ul><Link href="/admin/phan-quyen">Quản lý quyền truy cập →</Link></section></div>}
 </>}
 </main><footer className="admin-footer">CNKT Events · Ban tổ chức · Dữ liệu cá nhân chỉ phục vụ vận hành chương trình.</footer></SidebarInset><Toaster richColors position="top-right"/>
 <Dialog open={!!modal} onOpenChange={v=>!v&&setModal(null)}><DialogContent className="hub-dialog"><DialogHeader><DialogTitle>{modal?.kind==="participant"?"Chi tiết người tham dự":modal?.id||modal?.email?"Chỉnh sửa thông tin":"Thêm thông tin"}</DialogTitle><DialogDescription>{modal?.kind==="participant"?"Thông tin dùng cho đối soát vé.":"Kiểm tra đúng sự kiện trước khi lưu."}</DialogDescription></DialogHeader>{modal&&<ModalForm key={modal.id||modal.email||modal.kind} value={modal} data={data||{events:[],teams:[],stations:[]}} busy={busy} error={formError} save={mutate}/>}</DialogContent></Dialog>
 <AlertDialog open={!!cancel} onOpenChange={v=>!v&&setCancel(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Hủy vé của {cancel?.full_name}?</AlertDialogTitle><AlertDialogDescription>Vé sẽ mất hiệu lực và suất được trả lại. Dữ liệu được giữ trong hệ thống để đối soát.</AlertDialogDescription></AlertDialogHeader><label className="field">Lý do hủy<Input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Nhập ít nhất 3 ký tự"/></label><AlertDialogFooter><AlertDialogCancel>Quay lại</AlertDialogCancel><AlertDialogAction disabled={busy||reason.trim().length<3} onClick={async e=>{e.preventDefault();if(await mutate("cancel",{id:cancel?.id,reason}))setCancel(null);}}>Xác nhận hủy vé</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </SidebarProvider>;
}
function ArrowRightIcon(){return <ArrowUpRight size={16}/>;}
function Field({title,children,wide=false}:{title:string;children:ReactNode;wide?:boolean}){return <label className={"field "+(wide?"wide":"")}>{title}{children}</label>;}
function EventEditor({event:e,isNew,busy,error,save}:{event?:Row;isNew:boolean;busy:boolean;error:string;save:(v:Row)=>Promise<boolean>}){
 if(!e&&!isNew)return <Empty title="Không tìm thấy sự kiện"/>;
 async function submit(ev:FormEvent<HTMLFormElement>){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.currentTarget));const ok=await save({...f,id:e?.id,capacity:f.capacity?Number(f.capacity):null,event_date:f.event_date||null,event_time:f.event_time||null});if(ok&&isNew)window.location.href="/admin/su-kien";}
 return <><Link className="back-link" href="/admin/su-kien"><ArrowLeft size={16}/>Danh sách sự kiện</Link><form className="panel editor-panel" onSubmit={submit}><h2>{isNew?"Thông tin sự kiện mới":e?.title}</h2><div className="form-grid"><Field title="Tên sự kiện *" wide><Input name="title" defaultValue={e?.title} required minLength={4}/></Field><Field title="Loại chương trình"><Input name="event_type" defaultValue={e?.event_type||"Sự kiện khoa"}/></Field><Field title="Đối tượng tham dự *"><Input name="audience" defaultValue={e?.audience||"Sinh viên K26 CN&KT"} required/></Field><Field title="Địa điểm *" wide><Input name="venue" defaultValue={e?.venue} required/></Field><Field title="Ngày tổ chức"><Input type="date" name="event_date" defaultValue={e?.event_date||""}/></Field><Field title="Giờ tập trung (UTC+7)"><Input type="time" name="event_time" defaultValue={e?.event_time||""}/></Field><Field title="Số suất (trống = không giới hạn)"><Input name="capacity" type="number" min="1" defaultValue={e?.capacity||""}/></Field><Field title="Trạng thái"><NativeSelect name="status" defaultValue={e?.status||"DRAFT"}>{["DRAFT","COMING_SOON","REGISTRATION_OPEN","CLOSED","COMPLETED"].map(s=><NativeSelectOption key={s} value={s}>{labels[s]}</NativeSelectOption>)}</NativeSelect></Field><Field title="Nội dung giới thiệu" wide><Textarea name="description" defaultValue={e?.description} rows={6}/></Field></div><div className="info-banner">Chỉ mở đăng ký khi đã chốt ngày, giờ và địa điểm. Bản nháp không xuất hiện ở cổng sinh viên.</div>{error&&<p className="error-box">{error}</p>}<Button type="submit" disabled={busy}><Save/>{busy?"Đang lưu...":"Lưu sự kiện"}</Button>{e?.status!=="DRAFT"&&e?.slug&&<Button asChild variant="outline"><Link href={"/su-kien/"+e.slug}>Xem trang sinh viên<ArrowUpRight/></Link></Button>}</form></>;
}
function Checkin({events,busy,allowed,save}:{events:Row[];busy:boolean;allowed:boolean;save:(b:Row)=>Promise<boolean>}){const[eventId,setEvent]=useState("");const[code,setCode]=useState("");const[result,setResult]=useState("");async function submit(e:FormEvent){e.preventDefault();const ok=await save({eventId,ticketCode:code.trim().split("/").pop()});setResult(ok?"Đã ghi nhận có mặt. Bạn có thể tiếp tục check-in vé tiếp theo.":"Không ghi nhận check-in. Kiểm tra thông báo và thử lại.");if(ok)setCode("");}return <div className="admin-split"><form onSubmit={submit} className="panel checkin-panel"><div className="scan-icon"><ScanLine size={36}/></div><h2>Check-in người tham dự</h2><p>Chọn sự kiện, nhập mã vé hoặc dùng máy quét mã có chế độ nhập bàn phím.</p><Field title="Sự kiện"><Pick value={eventId} onChange={setEvent} options={events}/></Field><Field title="Mã vé / đường dẫn vé"><Input value={code} onChange={e=>setCode(e.target.value)} required placeholder="Nhập hoặc dán mã vé..." autoComplete="off"/></Field><Button type="submit" disabled={busy||!eventId||!allowed}><ScanLine/>{busy?"Đang đối soát...":"Xác nhận check-in"}</Button>{!allowed&&<p className="error-box">Vai trò hiện tại chỉ được xem, không được check-in.</p>}{result&&<p role="status" className="info-banner">{result}</p>}</form><section className="panel"><h2>Quy trình tại cổng</h2><ol className="check-list"><li>Chọn đúng sự kiện đang tiếp nhận.</li><li>Nhận mã vé từ màn hình hoặc bản in của sinh viên.</li><li>Kiểm tra phản hồi: hợp lệ, đã check-in, đã hủy hoặc sai sự kiện.</li><li>Vé chỉ được ghi nhận một lần. Không check-in hộ.</li></ol><hr/><p className="muted">Chưa hỗ trợ quét QR bằng camera. Không lưu check-in ngoại tuyến; cần kết nối mạng để đối soát chính xác.</p><Link href="/admin/sinh-vien">Mở danh sách đối soát →</Link></section></div>;}
function ModalForm({value:v,data,busy,error,save}:{value:Row;data:Row;busy:boolean;error:string;save:(action:string,b:Row)=>Promise<boolean>}){
 const[eventId,setEvent]=useState(v.event_id||data.teams.find((t:Row)=>t.id===v.team_id)?.event_id||"");const[published,setPublished]=useState(!!v.published);
 if(v.kind==="participant")return <div><dl className="settings-list">{[["Họ và tên",v.full_name],["MSSV",v.student_id],["Lớp",v.class_name],["Điện thoại",v.phone],["Email",v.email],["Trạng thái",labels[v.status]],["Đội",v.team_name||"Chưa phân đội"],["Check-in",v.checked_in_at?time(v.checked_in_at):"Chưa check-in"]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl><Button asChild><Link href={"/ve/"+v.ticket_code}>Xem vé</Link></Button></div>;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const map:Row={doi:"teams",tram:"stations",score:"scores","thong-bao":"notices","phan-quyen":"members"};const b:Row={...f,id:v.id,event_id:eventId||null,published};if("station_number"in f)b.station_number=Number(f.station_number);if("points"in f)b.points=Number(f.points);await save(map[v.kind],b);}
 return <form onSubmit={submit} className="modal-form">
 {["doi","tram","score","thong-bao"].includes(v.kind)&&<Field title={v.kind==="thong-bao"?"Sự kiện (trống = toàn khoa)":"Sự kiện *"}><Pick value={eventId} onChange={setEvent} options={data.events}/></Field>}
 {v.kind==="doi"&&<Field title="Tên đội *"><Input name="name" required minLength={2} defaultValue={v.name} placeholder="Ví dụ: Đội Bứt Phá"/></Field>}
 {v.kind==="tram"&&<><Field title="Số thứ tự trạm *"><Input name="station_number" type="number" min="1" max="100" required defaultValue={v.station_number}/></Field><Field title="Tên trạm *"><Input name="title" required defaultValue={v.title}/></Field><Field title="Mô tả / hướng dẫn"><Textarea name="description" defaultValue={v.description}/></Field></>}
 {v.kind==="score"&&<><Field title="Đội *"><NativeSelect name="team_id" defaultValue={v.team_id||""} required><NativeSelectOption value="">Chọn đội</NativeSelectOption>{data.teams.filter((t:Row)=>t.event_id===eventId).map((t:Row)=><NativeSelectOption key={t.id} value={t.id}>{t.name}</NativeSelectOption>)}</NativeSelect></Field><Field title="Trạm *"><NativeSelect name="station_id" defaultValue={v.station_id||""} required><NativeSelectOption value="">Chọn trạm</NativeSelectOption>{data.stations.filter((s:Row)=>s.event_id===eventId).map((s:Row)=><NativeSelectOption key={s.id} value={s.id}>{s.station_number}. {s.title}</NativeSelectOption>)}</NativeSelect></Field><Field title="Điểm (0–100) *"><Input name="points" type="number" min="0" max="100" defaultValue={v.points} required/></Field><Field title="Ghi chú / lý do điều chỉnh"><Textarea name="note" defaultValue={v.note||""}/></Field></>}
 {v.kind==="thong-bao"&&<><Field title="Tiêu đề *"><Input name="title" defaultValue={v.title} required/></Field><Field title="Nội dung *"><Textarea rows={6} name="body" defaultValue={v.body} required/></Field><label className="consent"><Switch checked={published} onCheckedChange={setPublished}/>Công bố trên cổng sinh viên</label></>}
 {v.kind==="phan-quyen"&&<><Field title="Họ và tên *"><Input name="name" defaultValue={v.name} required/></Field><Field title="Email đăng nhập *"><Input name="email" type="email" defaultValue={v.email} readOnly={!!v.email} required/></Field><Field title="Vai trò"><NativeSelect name="role" defaultValue={v.role||"VIEWER"}>{["ADMIN","CHECKIN","STATION","VIEWER",...(v.email?["REVOKED"]:[])].map(r=><NativeSelectOption key={r} value={r}>{labels[r]||"Thu hồi quyền"}</NativeSelectOption>)}</NativeSelect></Field><p className="muted">Chỉ lưu quyền trong ứng dụng, không gửi lời mời hay email.</p></>}
 {error&&<p role="alert" className="error-box">{error}</p>}<Button type="submit" disabled={busy||(["doi","tram","score"].includes(v.kind)&&!eventId)}><Save/>{busy?"Đang lưu...":"Lưu thông tin"}</Button></form>;
}
