"use client";
import { useEffect,useState, type FormEvent } from 'react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Switch } from '@/components/ui/switch';
import { NativeSelect,NativeSelectOption } from '@/components/ui/native-select';
import { DataTable,LoadState,Metric,useHub,type Row } from '@/components/hub-shared';
import { schedule,scoreBoard,recommendedCycle,type FieldState } from '@/lib/fieldmath';
const clock=(s:string)=>new Date(s).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Ho_Chi_Minh'});
const defaultState:FieldState={teams:[],cycle:recommendedCycle,start:'2026-09-13T15:10',play:6,decode:5,move:10,loser:'',attempts:[],order:[],battles:[],answers:[]};
function saveFile(name:string,value:string,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob(['\uFEFF'+value],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const csvCell=(v:unknown)=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';
function csv(name:string,rows:unknown[][]){saveFile(name,rows.map(r=>r.map(csvCell).join(',')).join('\r\n'),'text/csv;charset=utf-8');}
export function FieldPages({route,manager}:{route:string;manager:boolean}){
 if(!manager)return <p className="info-banner">Bộ mật thư và điều phối chỉ dành cho quản lý BTC.</p>;
 return <FieldWorkspace route={route}/>;
}
function FieldWorkspace({route}:{route:string}){
 const {data,error,loading,reload}=useHub('/api/fieldkit');const [draft,setDraft]=useState<FieldState>(defaultState);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const [from,setFrom]=useState('all');const [to,setTo]=useState('all');const [reveal,setReveal]=useState(false);const [printTeam,setPrintTeam]=useState('');
 useEffect(()=>{if(data)setDraft(data.state||{...defaultState,teams:data.teams.map((t:Row,i:number)=>({...t,start:i+1})),loser:data.teams[3]?.id||''});},[data]);
 async function mutate(action:string,value:unknown={}){setBusy(true);setMessage('');try{const r=await fetch('/api/fieldkit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,value,revision:data?.revision||0})});const d=await r.json() as Row;if(!r.ok)throw new Error(d.message);await reload();setMessage('Đã lưu dữ liệu.');return true;}catch(e){setMessage(e instanceof Error?e.message:'Chưa lưu được.');return false;}finally{setBusy(false);}}
 if(!data)return <LoadState {...{error,loading,reload}}/>;
 const state:FieldState|null=data.state;let rounds:ReturnType<typeof schedule>=[];let scheduleError='';try{if(draft.teams.length===7)rounds=schedule(draft);}catch(e){scheduleError=e instanceof Error?e.message:'';}
 const name=(id:string)=>state?.teams.find(t=>t.id===id)?.name||id;
 const allCards:Row[]=[...data.bank,...data.returns];
 let cards:Row[]=allCards.filter(c=>(from==='all'||c.from===Number(from))&&(to==='all'||c.to===Number(to)));
 if(printTeam&&state){const sr=schedule(state);const team=state.teams.find(t=>t.id===printTeam);cards=team?[data.bank.find((c:Row)=>c.from===0&&c.to===team.start),...sr.map(r=>{const t=r.teams.find(t=>t.id===team.id)!;return allCards.find(c=>c.from===t.station&&c.to===t.next);})]:[];}
 const board=state?scoreBoard(state):[];
 const locked=!!state?.attempts.length;
 return <div className="field-workspace"><nav className="field-nav print-hide" aria-label="Vận hành Teambuilding">{[['dieu-phoi','Lộ trình & bản đồ'],['mat-thu','Kho mật thư'],['thoi-gian','Kết quả trạm'],['khieu-chien','Khiêu chiến & giải cuối'],['kich-ban','Kịch bản & ý tưởng']].map(([slug,title])=><Link key={slug} href={'/admin/'+slug} aria-current={route===slug?'page':undefined}>{title}</Link>)}</nav>{message&&<p role="status" className="info-banner print-hide">{message}</p>}{error&&<p role="alert" className="error-box">{error}</p>}
 {route==='dieu-phoi'&&<><div className="metric-grid"><Metric label="Quy mô" value="105" caption="7 đội · dự kiến 15 sinh viên/đội"/><Metric label="Trạm vòng xoay" value="7" caption="A9 là điểm xuất phát và về đích"/><Metric label="Thời lượng một lượt" value={(draft.play+draft.decode+draft.move)+' phút'} caption="Cấu hình dự kiến, cần khảo sát"/><Metric label="Trạng thái lịch" value={locked?'Đã khóa':state?'Đã lưu':'Chưa lưu'} caption="Khóa khi có kết quả trạm đầu tiên"/></div>
 <form className="panel" onSubmit={e=>{e.preventDefault();void mutate('config',draft);}}><h2>Xếp trạm xuất phát</h2><p>Đội thua minigame trung tâm nhận trạm 4 sau hình phạt nhẹ. Tất cả đội bắt đầu lượt 1 cùng giờ khi đã tới trạm.</p>{data.teams.length!==7&&<p className="error-box">Hiện có {data.teams.length} đội. <Link href="/admin/doi">Tạo đủ đúng 7 đội thuộc Teambuilding K26</Link> để lưu lịch.</p>}<div className="form-grid">{draft.teams.map((t,i)=><label className="field" key={t.id}>{t.name}<NativeSelect value={t.start} disabled={locked} onChange={e=>setDraft({...draft,teams:draft.teams.map((a,j)=>j===i?{...a,start:Number(e.target.value)}:a)})}>{[1,2,3,4,5,6,7].map(n=><NativeSelectOption key={n} value={n}>Trạm {n}</NativeSelectOption>)}</NativeSelect></label>)}<label className="field">Đội thua tại trung tâm<NativeSelect required value={draft.loser} disabled={locked} onChange={e=>setDraft({...draft,loser:e.target.value})}><NativeSelectOption value="">Chọn đội</NativeSelectOption>{draft.teams.map(t=><NativeSelectOption key={t.id} value={t.id}>{t.name}</NativeSelectOption>)}</NativeSelect></label><label className="field">Bắt đầu lượt 1 · giờ Việt Nam<Input required type="datetime-local" disabled={locked} value={draft.start} onChange={e=>setDraft({...draft,start:e.target.value})}/></label><label className="field">Vòng di chuyển<NativeSelect disabled={locked} value={draft.cycle.join(',')} onChange={e=>setDraft({...draft,cycle:e.target.value.split(',').map(Number)})}><NativeSelectOption value={recommendedCycle.join(',')}>1 → 2 → 3 → 7 → 6 → 4 → 5 → 1</NativeSelectOption><NativeSelectOption value="1,2,3,4,5,6,7">1 → 2 → 3 → 4 → 5 → 6 → 7 → 1</NativeSelectOption></NativeSelect></label>{([['play','Chơi mỗi trạm'],['decode','Giải mật thư'],['move','Di chuyển / chờ']] as const).map(([key,title])=><label className="field" key={key}>{title} (phút)<Input required type="number" min={key==='decode'?0:1} max={key==='move'?60:30} disabled={locked} value={draft[key]} onChange={e=>setDraft({...draft,[key]:Number(e.target.value)})}/></label>)}</div>{scheduleError&&<p className="error-box">{scheduleError}</p>}<Button disabled={busy||locked||draft.teams.length!==7||!!scheduleError}>Lưu lịch điều phối</Button><p className="cell-sub">Lịch bên dưới là xem trước theo biểu mẫu. Xuất CSV chỉ dùng lịch đã lưu.</p></form>
 {!!rounds.length&&<section className="panel"><div className="section-head"><h2>Lịch 7 lượt</h2><Button variant="outline" disabled={!state} onClick={()=>{if(state)csv('lich-tram-k26.csv',[['Lượt','Bắt đầu','Hết lượt',...state.teams.map(t=>t.name)],...schedule(state).map(r=>[r.round,clock(r.start),clock(r.end),...r.teams.map(t=>'Trạm '+t.station)])]);}}>Xuất lịch đã lưu</Button></div><DataTable headers={['Lượt','Giờ',...draft.teams.map(t=>t.name)]} rows={rounds.map(r=>[r.round,clock(r.start)+'–'+clock(r.end),...r.teams.map(t=>'T'+t.station)])}/><p className="info-banner">Hoán vị bảo đảm mỗi trạm nhận một đội trong từng lượt theo lịch. Đường di chuyển có thể giao nhau; BTC cần đi thử đường, bố trí điểm chờ và dùng hiệu lệnh chung. Lượt 7 kết thúc bằng di chuyển về A9.</p></section>}
 <section className="panel"><h2>Điểm hẹn trong khuôn viên</h2><p>Tọa độ do BTC cung cấp. Ảnh sơ đồ là hình minh họa, không phải bản đồ dẫn đường theo GPS.</p><img className="campus-map" src="/campus-map.png" alt="Sơ đồ chỉ dẫn Đại học Đồng Tháp do Ban tổ chức cung cấp"/><DataTable headers={['Trạm','Địa điểm','Tọa độ','Bản đồ']} rows={data.destinations.map((d:Row)=>[d.id?'T'+d.id:'Trung tâm',d.name,d.lat.toFixed(6)+', '+d.lng.toFixed(6),<a href={'https://www.google.com/maps/search/?api=1&query='+d.lat+','+d.lng} target="_blank" rel="noreferrer">Mở vị trí</a>])}/><p className="info-banner">A9 → hồ bơi ≈ 507 m, trạm 3 → 4 ≈ 455 m theo đường chim bay. Vòng đề xuất giảm chặng thẳng dài nhất xuống khoảng 330 m; chưa xác nhận lối đi bộ, cổng hoặc thời gian thực tế.</p></section></>}
 {route==='mat-thu'&&<><section className="panel print-hide"><h2>49 hướng mật thư + 7 thẻ về trung tâm</h2><p>7 thẻ xuất phát và 42 hướng giữa các trạm. Khi chạy một vòng cố định: mỗi đội nhận 1 thẻ xuất phát, 6 thẻ chuyển trạm và 1 thẻ về A9 — tổng 56 lượt phát cho 7 đội.</p><div className="toolbar"><label className="field">Nơi phát<NativeSelect value={from} onChange={e=>{setFrom(e.target.value);setPrintTeam('');}}><NativeSelectOption value="all">Tất cả</NativeSelectOption>{data.destinations.map((d:Row)=><NativeSelectOption key={d.id} value={d.id}>{d.id?'Trạm '+d.id:'Trung tâm'}</NativeSelectOption>)}</NativeSelect></label><label className="field">Nơi đến<NativeSelect value={to} onChange={e=>{setTo(e.target.value);setPrintTeam('');}}><NativeSelectOption value="all">Tất cả</NativeSelectOption>{data.destinations.map((d:Row)=><NativeSelectOption key={d.id} value={d.id}>{d.id?'Trạm '+d.id:'Về A9'}</NativeSelectOption>)}</NativeSelect></label><label className="field">Bộ theo đội đã lưu<NativeSelect value={printTeam} onChange={e=>setPrintTeam(e.target.value)}><NativeSelectOption value="">Theo bộ lọc</NativeSelectOption>{state?.teams.map(t=><NativeSelectOption key={t.id} value={t.id}>{t.name} · 8 thẻ</NativeSelectOption>)}</NativeSelect></label><Button variant="outline" onClick={()=>window.print()}>In {cards.length} thẻ cho người chơi</Button></div><label className="consent"><Switch checked={reveal} onCheckedChange={setReveal}/>Hiện lời giải dành cho BTC (không xuất hiện trên bản in)</label><p>Phần địa điểm dẫn tới trạm tiếp theo. Phần mảnh ghép thuộc trạm vừa hoàn thành; thẻ về A9 vẫn giữ mảnh của trạm cuối. Mã Cxy dành riêng cho BTC, không in lên thẻ người chơi.</p></section>
 <section className="panel field-decoder"><h2>Bảng tra cứu của đội</h2><p>{data.decoder}</p><DataTable headers={['Mã','Địa điểm','Tọa độ']} rows={data.destinations.map((d:Row)=>['D0'+d.id,d.name,d.lat.toFixed(6)+', '+d.lng.toFixed(6)])}/></section>
 <div className="cipher-grid">{cards.map((c,i)=><article className="panel cipher-card" key={c.id}><div className="cipher-admin print-hide"><b>{c.id} · {c.from?'Trạm '+c.from:'Trung tâm'} → {c.to?'Trạm '+c.to:'A9'}</b><span>{c.method}</span></div><div className="cipher-print-label">{printTeam?name(printTeam):'Teambuilding K26'} · Phiếu {i+1}</div><h2>A / Giải điểm đến</h2><p>{c.route}</p><h2>B / Mảnh mang về</h2><p className="prose-text">{c.fragment}</p><p className="cipher-answer-line">Địa điểm: ____________________<br/>Mảnh ghép: __________________</p>{reveal&&<aside className="cipher-solution print-hide"><strong>{c.solution}</strong><p>Gợi ý 1: {c.hint1}</p><p>Gợi ý 2: {c.hint2}</p></aside>}</article>)}</div><p className="print-hide info-banner">Đây là 7 nhóm phương pháp với tham số theo hướng đi; không phải 49 kỹ thuật hoàn toàn khác nhau. Phát riêng từng phiếu tại thời điểm hợp lệ để tránh đội đọc trước toàn bộ mảnh ghép.</p></>}
 {route==='thoi-gian'&&(!state?<p className="info-banner">Lưu lịch điều phối trước khi ghi kết quả trạm.</p>:<><div className="metric-grid"><Metric label="Kết quả đã ghi" value={state.attempts.length+'/49'}/><Metric label="Đội hoàn tất 7 trạm" value={board.filter(t=>t.completed===7).length+'/7'}/><Metric label="Giới hạn chơi" value={state.play*60+' giây'}/><Metric label="Điểm thưởng đã trao" value={state.battles.length}/></div><form className="panel" onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await mutate('attempt',{team:f.get('team'),station:Number(f.get('station')),seconds:Number(f.get('seconds')),dnf:f.get('status')==='dnf'});}}><h2>Ghi thời gian hoàn thành</h2><p>Đo thời gian chơi, loại trừ đi bộ, chờ trạm, giải mật thư và hình phạt ở trung tâm. Lưu lại cùng đội/trạm sẽ sửa kết quả cũ.</p><div className="form-grid"><TeamSelect teams={state.teams}/><label className="field">Trạm<NativeSelect name="station">{[1,2,3,4,5,6,7].map(n=><NativeSelectOption key={n} value={n}>Trạm {n}</NativeSelectOption>)}</NativeSelect></label><label className="field">Trạng thái<NativeSelect name="status"><NativeSelectOption value="done">Hoàn thành</NativeSelectOption><NativeSelectOption value="dnf">Hết giờ / không hoàn thành</NativeSelectOption></NativeSelect></label><label className="field">Thời gian (giây)<Input name="seconds" type="number" step="0.01" min="0" max={state.play*60} defaultValue="0" required/></label></div><Button disabled={busy||!!state.order.length||!!state.answers.length}>Lưu kết quả</Button></form><section className="panel"><h2>Bảng điểm Tổng lực</h2><p>Mỗi trạm chỉ cộng điểm sau khi đủ 7 kết quả. Nhanh nhất 7 điểm, tiếp theo 6…1. Đồng thời gian chia trung bình điểm của các vị trí chiếm chỗ; DNF nhận 0 điểm. Khiêu chiến thắng +1.</p><DataTable headers={['Đội','Đã ghi','DNF','Giây chơi','Điểm trạm','Thưởng','Tổng']} rows={board.map(t=>[t.name,t.completed+'/7',t.dnf,t.seconds.toFixed(2),t.points,t.bonus,<strong>{t.total}</strong>])}/><Button variant="outline" onClick={()=>csv('ket-qua-tram.csv',[['Đội','Trạm','Giây','DNF'],...state.attempts.map(a=>[name(a.team),a.station,a.seconds,a.dnf?'Có':'Không'])])}>Xuất kết quả CSV</Button><p className="info-banner">Đây là bảng điểm riêng cho thể thức 7 trạm; không cộng chồng với điểm 0–100 ở trang Chấm điểm chung. Nếu không giải được mật thư, xét ít DNF hơn rồi tổng thời gian chơi thấp hơn theo kịch bản.</p></section><DataTable headers={['Đội','Trạm','Giây','Trạng thái']} rows={[...state.attempts].sort((a,b)=>a.station-b.station).map(a=>[name(a.team),a.station,a.seconds,a.dnf?'DNF':'Hoàn thành'])}/></>)}
 {route==='khieu-chien'&&(!state?<p className="info-banner">Lưu lịch và ghi kết quả trạm trước khi mở vòng cuối.</p>:<><section className="panel"><h2>Thứ tự khiêu chiến</h2><p>Mỗi đội có một lượt tấn công; không giới hạn số lần nhận thách đấu trong 7 lượt. Từ chối: đội khiêu chiến thắng. Mỗi chiến thắng cộng 1 điểm và nhận gợi ý tiếp theo của riêng đội đó.</p><Button disabled={busy||state.attempts.length!==49||!!state.order.length||state.answers.some(a=>a.correct)} onClick={()=>mutate('draw')}>Bốc thăm thứ tự 7 đội</Button>{!!state.order.length&&<ol className="check-list">{state.order.map((id,i)=><li key={id}>{i+1}. {name(id)} — {i<state.battles.length?'Đã khiêu chiến':i===state.battles.length?'Đến lượt':'Đang chờ'}</li>)}</ol>}</section>
 {!!state.order[state.battles.length]&&<BattleForm key={state.battles.length} state={state} busy={busy} save={v=>mutate('battle',v)}/>}
 {!!state.battles.length&&<section className="panel"><h2>Kết quả và gợi ý đã nhận</h2><DataTable headers={['Lượt','Khiêu chiến','Phòng thủ','Đội thắng','Lý do']} rows={state.battles.map((b,i)=>[i+1,name(b.attacker),name(b.defender),name(b.winner),b.refused?'Đối thủ từ chối':'Thắng minigame'])}/>{board.filter(t=>t.bonus>0).map(t=><details key={t.id} className="hint-detail"><summary>{t.name} · {t.bonus} gợi ý (BTC mở riêng)</summary>{data.bonusHints.slice(0,t.bonus).map((h:string,i:number)=><p key={h}>H{i+1}: {h}</p>)}</details>)}</section>}
 <form className="panel" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await mutate('answer',{team:f.get('team'),answer:f.get('answer')});}}><h2>Tiếp nhận lời giải cuối tại A9</h2><p>Chỉ nhập khi đội đã có đủ 7 dấu trạm. BTC nhận bài đồng thời trong cửa sổ chung; thời điểm bên dưới là lúc BTC lưu, không tự dùng để phân thắng thua nếu các bài được nhận cùng lúc.</p><div className="form-grid"><TeamSelect teams={state.teams}/><label className="field">Câu trả lời của đội<Input name="answer" required minLength={2} maxLength={200}/></label></div><Button disabled={busy||state.attempts.length!==49||(state.order.length>0&&state.battles.length!==7)}>Kiểm tra & ghi nhận</Button><DataTable headers={['Đội','Kết quả','Thời điểm BTC lưu']} rows={state.answers.map(a=>[name(a.team),a.correct?'Chính xác':'Chưa chính xác',clock(a.at)])}/></form><p className="info-banner">Nếu đã bắt đầu khiêu chiến, hoàn tất đủ 7 lượt rồi mở lượt giải chung. Nếu không đội nào giải được: ít DNF hơn → tổng thời gian chơi thấp hơn → tổng điểm cao hơn → đồng hạng nếu vẫn bằng nhau. Thể lệ cần công bố trước chương trình.</p></>)}
 {route==='kich-ban'&&<><section className="panel"><h2>Kịch bản đề xuất · 13/09/2026</h2><DataTable headers={['Mốc','Hoạt động']} rows={[["14:45–14:58","Tập trung A9, chia 7 đội x 15 sinh viên, phổ biến luật và minigame trung tâm."],["14:58–15:10","Đội thua làm thử thách nhẹ 45–60 giây rồi nhận trạm 4. Sáu đội còn lại nhận 1, 2, 3, 5, 6, 7. Di chuyển, trọng tài xác nhận đủ đội."],["15:10–17:16","7 lượt x 18 phút = 6 phút chơi + 2 phút mật thư + 10 phút đi/chờ. Lượt cuối về A9. Đây là lịch dự kiến."],["Sau khi đủ 7 đội","Giải chung 3 phút. Nếu chưa có lời giải đúng: bốc thăm, 7 lượt khiêu chiến, rồi giải chung thêm 2 phút."],["Kết thúc","Đối soát kết quả, phân giải Mật thư và Tổng lực theo thể lệ đã công bố."]]}/><p>Tại hồ bơi, mặc định đặt chậu tìm bi ở khu khô được phép sử dụng; không yêu cầu xuống nước. Hình phạt trung tâm có thể là tạo dáng đồng đội hoặc hô khẩu hiệu, có lựa chọn thay thế.</p><p>Minigame khiêu chiến: mỗi bên 2 đại diện ghép cùng một bộ 4 mảnh trong 60 giây. Hòa dùng câu phụ 30 giây, sau đó bốc thăm đã công bố. Chuẩn bị 7 bộ tương đương; không trao thưởng hai lần cho cùng trận.</p></section><section className="panel"><h2>Cấu trúc câu cuối dành cho BTC</h2><p><strong>{data.finalText}</strong></p><p>{data.finalContext}</p><p>{data.fragmentText} Có 7 mảnh; khi ghép đủ tạo thành 10 từ. Bản in không ghi thứ tự ghép để giữ phần suy luận cuối.</p><p>Thẻ đầu ở A9 chỉ cho lời chúc KHỞI HÀNH. Sau mỗi trạm, phát mảnh của chính trạm vừa chơi. Thẻ cuối thay điểm đến bằng A9 để không thiếu mảnh của trạm thứ bảy.</p></section><section className="panel"><h2>Kho ý tưởng liên môn</h2><p>Các dòng ghi “mẫu” cần BTC hoàn thiện nguồn và đáp án trước khi phát. Dùng phiếu dữ kiện in để mọi đội có cùng thông tin; không bắt buộc truy cập mạng.</p><DataTable headers={['Lĩnh vực','Nội dung / cách làm','Lời giải / biên soạn']} rows={data.ideas}/></section><section className="panel"><h2>Chốt thể lệ trước ngày chơi</h2><ul className="check-list"><li>Hai bảng: giải Mật thư xét lời giải; giải Tổng lực xét điểm trạm + điểm khiêu chiến. Nếu chỉ trao một giải, BTC cần chọn rõ tiêu chí ưu tiên.</li><li>DNF: 0 điểm trạm, quy đổi bằng giới hạn chơi khi xét thời gian; so số DNF trước tổng thời gian.</li><li>Tổng điểm trạm tối đa 49; một đội có thể thắng tối đa 7 trận khiêu chiến/phòng thủ nên tối đa lý thuyết 56 điểm.</li><li>Chốt tiêu chí hoàn thành từng trò và cách đo thời gian trước khi đội đầu vào trạm.</li><li>Đội đến sớm chờ ở khu vực riêng; trễ dây chuyền thì BTC dừng và điều chỉnh đồng bộ, không tự chuyển trạm.</li><li>Khóa bộ tin, văn bản và thông tin ngành theo ngày; lưu nguồn chính thức và người duyệt từng câu hỏi.</li></ul></section></>}
 </div>;
}
function TeamSelect({teams}:{teams:{id:string;name:string}[]}){return <label className="field">Đội<NativeSelect name="team" required>{teams.map(t=><NativeSelectOption key={t.id} value={t.id}>{t.name}</NativeSelectOption>)}</NativeSelect></label>;}
function BattleForm({state,busy,save}:{state:FieldState;busy:boolean;save:(v:Row)=>Promise<boolean>}){const attacker=state.order[state.battles.length];const [defender,setDefender]=useState(state.teams.find(t=>t.id!==attacker)!.id);const [outcome,setOutcome]=useState('attack');return <form className="panel" onSubmit={e=>{e.preventDefault();void save({defender,winner:outcome==='defense'?defender:attacker,refused:outcome==='refuse'});}}><h2>Lượt {state.battles.length+1} · {state.teams.find(t=>t.id===attacker)?.name} khiêu chiến</h2><div className="form-grid"><label className="field">Đội nhận khiêu chiến<NativeSelect value={defender} onChange={e=>setDefender(e.target.value)}>{state.teams.filter(t=>t.id!==attacker).map(t=><NativeSelectOption key={t.id} value={t.id}>{t.name}</NativeSelectOption>)}</NativeSelect></label><label className="field">Kết quả<NativeSelect value={outcome} onChange={e=>setOutcome(e.target.value)}><NativeSelectOption value="attack">Đội khiêu chiến thắng</NativeSelectOption><NativeSelectOption value="defense">Đội phòng thủ thắng</NativeSelectOption><NativeSelectOption value="refuse">Đối thủ từ chối</NativeSelectOption></NativeSelect></label></div><Button disabled={busy}>Chốt trận & trao 1 điểm</Button><p className="cell-sub">Chỉ chốt sau khi hai đội và trọng tài xác nhận. Kết quả đã chốt không sửa trong màn hình này.</p></form>;}
