"use client";
import { useEffect,useState, type ReactNode } from "react";
import Link from "next/link";
import { CalendarDays, ArrowUpRight, MapPin, Ticket, Search, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { NativeSelect,NativeSelectOption } from "@/components/ui/native-select";
import { Skeleton } from "@/components/ui/skeleton";
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table";
export type Row=Record<string,any>;
export const labels:Record<string,string>={REGISTRATION_OPEN:"Đang mở đăng ký",COMING_SOON:"Sắp diễn ra",DRAFT:"Bản nháp",CLOSED:"Đã đóng đăng ký",COMPLETED:"Đã kết thúc",CANCELLED:"Đã hủy",REGISTERED:"Đã giữ chỗ",OWNER:"Chủ sở hữu",ADMIN:"Quản lý",CHECKIN:"Check-in",STATION:"Trọng tài",VIEWER:"Xem tổng quan"};
export function useHub(endpoint:string){const[data,setData]=useState<Row|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(true);async function reload(){setError("");try{const r=await fetch(endpoint,{cache:"no-store"});const d=await r.json() as Row;if(!r.ok)throw new Error(d.message);setData(d);}catch(e){setError(e instanceof Error?e.message:"Không thể tải dữ liệu.");}finally{setLoading(false);}}useEffect(()=>{void reload();},[endpoint]);return {data,error,loading,reload};}
export function date(s:string|null){return s ? new Date(s+"T00:00:00+07:00").toLocaleDateString("vi-VN",{day:"2-digit",month:"2-digit",year:"numeric",timeZone:"Asia/Ho_Chi_Minh"}):"Chưa chốt ngày";}
export function time(s:string){return new Date(s).toLocaleString("vi-VN",{timeZone:"Asia/Ho_Chi_Minh"});}
export function Pill({value}:{value:string}){return <span className={"pill "+(value==="REGISTRATION_OPEN"?"green":value==="CANCELLED"?"red":"")}>{labels[value]||value}</span>;}
export function Heading({eyebrow,title,text,children}:{eyebrow?:string;title:string;text?:string;children?:ReactNode}){return <div className="page-heading"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{text&&<p>{text}</p>}</div>{children}</div>;}
export function Empty({title="Chưa có dữ liệu",text="Dữ liệu sẽ xuất hiện tại đây khi có hoạt động.",children}:{title?:string;text?:string;children?:ReactNode}){return <div className="empty-box"><Ticket size={30}/><h3>{title}</h3><p>{text}</p>{children}</div>;}
export function LoadState({loading,error,reload}:{loading:boolean;error:string;reload:()=>void}){if(error)return <div className="error-box" role="alert">{error}<Button onClick={reload} variant="outline"><RefreshCw/>Thử lại</Button></div>;if(loading)return <div className="metric-grid">{[1,2,3,4].map(i=><Skeleton key={i} className="h-32 rounded-2xl"/>)}</div>;return null;}
export function Pick({value,onChange,options,label="Sự kiện",all=false}:{value:string;onChange:(v:string)=>void;options:Row[];label?:string;all?:boolean}){return <label className="pick"><span className="sr-only">{label}</span><NativeSelect aria-label={label} value={value} onChange={e=>onChange(e.target.value)}><NativeSelectOption value="">{all?"Tất cả sự kiện":"Chọn "+label.toLowerCase()}</NativeSelectOption>{options.map(o=><NativeSelectOption key={o.id} value={o.id}>{o.title||o.name}</NativeSelectOption>)}</NativeSelect></label>;}
export function DataTable({headers,rows}:{headers:string[];rows:ReactNode[][]}){return <div className="table-box"><Table><TableHeader><TableRow>{headers.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((row,i)=><TableRow key={i}>{row.map((c,j)=><TableCell key={j}>{c}</TableCell>)}</TableRow>)}</TableBody></Table>{!rows.length&&<Empty title="Không có kết quả" text="Thử đổi bộ lọc hoặc thêm dữ liệu mới."/>}</div>;}
export function EventCard({e}:{e:Row}){return <article className="event-card"><div className={"event-banner "+(e.id==="gala-k26-2026"?"gala":"")}><div><span className="eyebrow">{e.event_type}</span><h2>{e.id==="gala-k26-2026"?"GALA":"TEAM / EVENT"}<br/><em>{e.short_title.includes("K26")?"K26":"CN&KT"}</em></h2></div><span className="event-year">20<br/>26</span><Pill value={e.status}/></div><div className="event-body"><h3><Link href={"/su-kien/"+e.slug}>{e.title}</Link></h3><p className="muted clamp">{e.description}</p><div className="meta"><CalendarDays/>{date(e.event_date)}{e.event_time&&" · "+e.event_time}</div><div className="meta"><MapPin/>{e.venue}</div><div className="event-bottom"><span><strong>{e.registered||0}</strong> / {e.capacity||"Không giới hạn"}<small>lượt giữ chỗ</small></span><Button asChild><Link href={"/su-kien/"+e.slug}>Xem sự kiện<ArrowUpRight/></Link></Button></div></div></article>;}
export function Metric({label,value,caption}:{label:string;value:ReactNode;caption?:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong>{caption&&<small>{caption}</small>}</div>;}
export function SearchBox({value,onChange,placeholder="Tìm kiếm..."}:{value:string;onChange:(s:string)=>void;placeholder?:string}){return <label className="search-box"><Search size={18}/><input aria-label={placeholder} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>;}
