"use client";
import { useState, type FormEvent } from "react";
import Link from "next/link";
import { ArrowRight, ArrowLeft, CalendarDays, CheckCircle2, MapPin, Phone, Trophy, Users, Ticket, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Accordion,AccordionItem,AccordionTrigger,AccordionContent } from "@/components/ui/accordion";
import { NativeSelect,NativeSelectOption } from "@/components/ui/native-select";
import { Heading,Empty,EventCard,DataTable,LoadState,Pick,Pill,SearchBox,useHub,date,time, type Row } from "@/components/hub-shared";
const nav=[["/su-kien","Sự kiện"],["/lich","Lịch hoạt động"],["/bang-xep-hang","Xếp hạng"],["/thong-bao","Thông báo"],["/ho-tro","Hỗ trợ"]];
export function PublicPages({path=[]}:{path?:string[]}) {
 const{data,error,loading,reload}=useHub("/api/hub/public");const[search,setSearch]=useState("");const[eventId,setEventId]=useState("");const[status,setStatus]=useState("all");
 const route=path[0]||"home"; const events:Row[]=data?.events||[];const e=events.find(e=>e.slug===path[1]);
 const filtered=events.filter(e=>(!search||(e.title+" "+e.audience).toLowerCase().includes(search.toLowerCase()))&&(status==="all"||e.status===status));
 return <div className="public-app"><header className="public-header"><Link href="/" className="brand"><b>KT<span>✦</span></b><div>CNKT <strong>EVENTS</strong><small>TRƯỜNG ĐẠI HỌC ĐỒNG THÁP</small></div></Link><nav>{nav.map(([href,title])=><Link className={route===href.slice(1)?"active":""} key={href} href={href}>{title}</Link>)}</nav><Button variant="outline" asChild><Link href="/tra-cuu"><Ticket/>Tra cứu vé</Link></Button></header><main className="public-main">
 {(route==="home"||(route==="su-kien"&&!path[1]))&&<><Heading eyebrow="KHOA CÔNG NGHỆ & KỸ THUẬT" title={route==="home"?"Hẹn bạn ở sự kiện tiếp theo.":"Khám phá sự kiện"} text="Kết nối bạn bè, trải nghiệm thử thách và tạo nên những kỷ niệm của K26."><span className="semester">NĂM HỌC<br/><strong>2026 — 2027</strong></span></Heading><div className="toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Tìm tên sự kiện, đối tượng..."/><NativeSelect aria-label="Trạng thái" value={status} onChange={e=>setStatus(e.target.value)}><NativeSelectOption value="all">Mọi trạng thái</NativeSelectOption><NativeSelectOption value="REGISTRATION_OPEN">Đang mở đăng ký</NativeSelectOption><NativeSelectOption value="COMING_SOON">Sắp diễn ra</NativeSelectOption><NativeSelectOption value="COMPLETED">Đã kết thúc</NativeSelectOption></NativeSelect></div><LoadState {...{error,loading,reload}}/>{data&&<div className="event-grid">{filtered.map(e=><EventCard key={e.id} e={e}/>)}</div>}{data&&!filtered.length&&<Empty title="Chưa có sự kiện phù hợp" text="BTC cần khởi tạo hoặc công bố sự kiện; bạn cũng có thể thử bộ lọc khác."/>}<section className="steps-strip"><div><span>01</span><h3>Chọn sự kiện</h3><p>Xem lịch, địa điểm và điều kiện tham gia.</p></div><div><span>02</span><h3>Giữ chỗ của bạn</h3><p>Đăng ký bằng thông tin sinh viên chính xác.</p></div><div><span>03</span><h3>Gặp nhau tại sự kiện</h3><p>Lưu mã vé và xuất trình khi check-in.</p></div></section></>}
 {route==="su-kien"&&path[1]&&<><Link className="back-link" href="/su-kien"><ArrowLeft size={16}/>Tất cả sự kiện</Link><LoadState {...{error,loading,reload}}/>{data&&!e&&<Empty title="Không tìm thấy sự kiện" text="Sự kiện có thể chưa được công bố."/>}{e&&(path[2]==="dang-ky"?<Registration event={e}/>:<><Heading eyebrow={e.event_type} title={e.title} text={e.audience}><Pill value={e.status}/></Heading><div className="detail-grid"><div><section className="panel"><h2>Về chương trình</h2><p className="prose-text">{e.description}</p><div className="info-grid"><div><CalendarDays/><b>{date(e.event_date)}</b><span>{e.event_time||"Giờ sẽ được công bố"} · giờ Việt Nam</span></div><div><MapPin/><b>{e.venue}</b><span>Địa điểm tổ chức</span></div></div></section>{(data?.stations||[]).some((s:Row)=>s.event_id===e.id)&&<section className="panel"><h2>Hành trình thử thách</h2><div className="station-list">{data?.stations.filter((s:Row)=>s.event_id===e.id).map((s:Row)=><div key={s.id}><b>{String(s.station_number).padStart(2,"0")}</b><span><strong>{s.title}</strong><p>{s.description}</p></span></div>)}</div></section>}<section className="panel"><h2>Chuẩn bị trước khi tham gia</h2><ul className="check-list"><li>Kiểm tra đúng sự kiện, MSSV và lớp trên vé.</li><li>Đến đúng điểm tập trung, xuất trình mã vé với BTC.</li>{e.id.startsWith("teambuilding")&&<><li>Trang phục tự do, lịch sự và thuận tiện vận động.</li><li>Mang thêm một bộ quần áo dự phòng.</li></>}</ul></section></div><aside className="registration-summary"><Ticket/><h2>Giữ chỗ tham gia</h2><div className="capacity"><strong>{e.registered}</strong><span> / {e.capacity||"Không giới hạn"}</span></div><p>{e.capacity?Math.max(0,e.capacity-e.registered)+" suất còn lại":"Dành cho "+e.audience}</p><Button asChild disabled={!e.registration_open}>{e.registration_open?<Link href={"/su-kien/"+e.slug+"/dang-ky"}>Đăng ký ngay<ArrowRight/></Link>:<span>Chưa nhận đăng ký</span>}</Button><small>Thông tin được lưu để BTC đối soát. Mã vé hiển thị ngay sau khi đăng ký.</small></aside></div></>)}</>}
 {route==="tra-cuu"&&<Lookup/>}
 {route==="lich"&&<><Heading eyebrow="LÊN LỊCH CÙNG KHOA" title="Lịch hoạt động" text="Thời gian hiển thị theo giờ Việt Nam. Sự kiện chưa chốt lịch được tách riêng."/><LoadState {...{error,loading,reload}}/><div className="agenda">{events.map(e=><Link key={e.id} href={"/su-kien/"+e.slug}><div className="date-block"><strong>{e.event_date?e.event_date.slice(8):"—"}</strong><span>{e.event_date?"THÁNG "+e.event_date.slice(5,7):"CHỜ LỊCH"}</span></div><div><Pill value={e.status}/><h2>{e.title}</h2><p>{e.event_time||"Chưa chốt giờ"} · {e.venue}</p></div><ArrowRight/></Link>)}</div>{data&&!events.length&&<Empty/>}</>}
 {route==="bang-xep-hang"&&<><Heading eyebrow="TEAMBUILDING · K26" title="Bảng xếp hạng" text="Tổng điểm các trạm đã chấm. Bằng điểm được xếp đồng hạng; thứ tự tên không phải tiêu chí phân thắng thua."/><div className="toolbar"><Pick value={eventId} onChange={setEventId} options={events} all/><Button variant="outline" onClick={reload}>Làm mới</Button></div><LoadState {...{error,loading,reload}}/>{data&&<DataTable headers={["Hạng","Đội","Số trạm đã chấm","Tổng điểm"]} rows={data.teams.filter((t:Row)=>!eventId||t.event_id===eventId).map((t:Row,_i:number,a:Row[])=>[<strong className="rank">#{1+a.filter(x=>x.points>t.points).length}</strong>,t.name,t.completed,<strong>{t.points} điểm</strong>])}/>}</>}
 {route==="thong-bao"&&<><Heading eyebrow="CẬP NHẬT TỪ BAN TỔ CHỨC" title="Thông báo" text="Theo dõi thay đổi lịch, hướng dẫn tham dự và thông tin chương trình."/><LoadState {...{error,loading,reload}}/>{data&&!data.notices.length&&<Empty title="Chưa có thông báo mới" text="Thông báo đã công bố của BTC sẽ xuất hiện tại đây."/>}<div className="notice-grid">{data?.notices.map((n:Row)=><article className="panel" key={n.id}><span className="eyebrow">{events.find(e=>e.id===n.event_id)?.short_title||"TOÀN KHOA"}</span><h2>{n.title}</h2><small>{time(n.created_at)}</small><p className="prose-text">{n.body}</p></article>)}</div></>}
 {route==="ho-tro"&&<><Heading eyebrow="CẦN THÊM THÔNG TIN?" title="Hỗ trợ tham gia" text="Những điều cần biết trước khi đăng ký và đến sự kiện."/><div className="detail-grid"><section className="panel"><h2>Câu hỏi thường gặp</h2><Accordion type="single" collapsible>{[["Một MSSV có thể đăng ký bao nhiêu lần?","Mỗi MSSV được đăng ký một lần cho mỗi sự kiện. Bạn có thể tham gia nhiều sự kiện khác nhau."],["Đã đăng ký nhưng chưa nhận được email?","Hệ thống hiện trả mã vé trực tiếp trên màn hình, chưa gửi email tự động. Lưu lại đường dẫn hoặc in vé ngay sau khi đăng ký."],["Tôi làm mất mã vé thì sao?","Liên hệ BTC và cung cấp MSSV, tên sự kiện để đối soát. Website không cho tìm dữ liệu cá nhân chỉ bằng MSSV."],["Tôi không thể tham dự hoặc nhập sai thông tin?","Liên hệ BTC trước chương trình. Việc hủy được ghi nhận trong nhật ký và trả lại suất; vé đã check-in không được hủy."],["Gala K26 diễn ra khi nào?","Ngày, giờ và địa điểm Gala chưa được xác nhận trong thông tin đầu vào. Theo dõi trang Gala và Thông báo để cập nhật."]].map(([q,a],i)=><AccordionItem key={q} value={String(i)}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></section><aside className="panel contact-panel"><Phone/><h2>Hỗ trợ Teambuilding</h2><strong>Trương Hữu Bằng</strong><a className="contact-phone" href="tel:0812582019">0812 582 019</a><p>Liên hệ khi không thể tham dự Teambuilding hoặc cần đối soát thông tin.</p><ShieldCheck/><small>Không chia sẻ đường dẫn vé công khai: đường dẫn chứa mã dùng để đối soát người tham dự.</small></aside></div></>}
 </main><footer className="public-footer"><div><strong>CNKT EVENTS</strong><p>Khoa Công nghệ và Kỹ thuật<br/>Trường Đại học Đồng Tháp</p></div><div><Link href="/ho-tro">Hỗ trợ & hướng dẫn</Link><Link href="/tra-cuu">Tra cứu vé</Link><Link href="/admin">Không gian Ban tổ chức<ArrowRight size={16}/></Link></div><small>2026 · Kết nối từ những trải nghiệm.</small></footer></div>;
}
function Lookup(){const[code,setCode]=useState("");function submit(e:FormEvent){e.preventDefault();const raw=code.trim().split("/").pop()||"";if(raw)window.location.href="/ve/"+encodeURIComponent(raw);}return <><Heading eyebrow="VÉ ĐIỆN TỬ" title="Vé của bạn ở đây." text="Nhập mã vé hoặc dán đường dẫn đã lưu sau khi đăng ký."/><form onSubmit={submit} className="lookup-panel panel"><Ticket size={38}/><h2>Tra cứu vé tham dự</h2><label className="field">Mã vé / đường dẫn vé<Input value={code} onChange={e=>setCode(e.target.value)} placeholder="TB26-..." required/></label><Button type="submit">Xem vé<ArrowRight/></Button><p>Mất mã vé? <Link href="/ho-tro">Liên hệ Ban tổ chức</Link> để được đối soát.</p></form></>;}
function Registration({event:e}:{event:Row}){const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const[confirmed,setConfirmed]=useState(false);const[code,setCode]=useState("");async function submit(ev:FormEvent<HTMLFormElement>){ev.preventDefault();if(!confirmed){setMessage("Vui lòng xác nhận tham dự.");return;}const f=new FormData(ev.currentTarget);setBusy(true);setMessage("");try{const r=await fetch("/api/registrations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...Object.fromEntries(f),eventId:e.id,confirmation:confirmed})});const d=await r.json() as Row;if(!r.ok)throw new Error(d.message);setCode(d.ticketCode);}catch(err){setMessage(err instanceof Error?err.message:"Chưa lưu được đăng ký.");}finally{setBusy(false);}}return <><Heading eyebrow="THÔNG TIN ĐĂNG KÝ" title={code?"Bạn đã giữ chỗ thành công!":"Đăng ký "+e.short_title} text={e.audience}/>{code?<section className="panel lookup-panel"><CheckCircle2 size={42}/><h2>Hẹn gặp bạn tại sự kiện</h2><p>Hãy lưu đường dẫn vé ngay. Hệ thống chưa gửi email tự động.</p><code className="ticket-code">{code}</code><Button asChild><Link href={"/ve/"+code}>Xem & in vé<Ticket/></Link></Button></section>:<div className="detail-grid"><form className="panel" onSubmit={submit}><h2>Thông tin người tham dự</h2><div className="form-grid">{[["studentId","Mã số sinh viên","text","6–12 chữ số"],["className","Lớp","text","Ví dụ: 26IT1"],["fullName","Họ và tên","text","Nhập đầy đủ họ tên"],["phone","Số điện thoại","tel","Số điện thoại liên hệ"],["email","Email liên hệ","email","Email dùng để đối soát"]].map(([name,title,type,placeholder])=><label className={"field "+(name==="fullName"?"wide":"")} key={name}>{title} *<Input name={name} type={type} placeholder={placeholder} required maxLength={name==="studentId"?12:100} pattern={name==="studentId"?"[0-9]{6,12}":undefined}/></label>)}<label className="honeypot" aria-hidden="true">Không điền mục này<Input name="website" tabIndex={-1} autoComplete="off"/></label></div><div className="consent"><Checkbox id="confirm-attendance" checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/><label htmlFor="confirm-attendance">Tôi xác nhận thông tin chính xác, chắc chắn có thể tham dự và đồng ý để BTC sử dụng thông tin cho việc vận hành sự kiện.</label></div>{message&&<p role="alert" className="error-box">{message}</p>}<Button type="submit" disabled={busy||!e.registration_open}>{busy?"Đang xác nhận...":e.registration_open?"Xác nhận đăng ký":"Đăng ký chưa mở"}<ArrowRight/></Button></form><aside className="panel"><h2>{e.title}</h2><p className="meta"><CalendarDays/>{date(e.event_date)} · {e.event_time}</p><p className="meta"><MapPin/>{e.venue}</p><p className="meta"><Users/>{e.capacity||"Toàn thể"} sinh viên</p><hr/><h3>Lưu ý trước khi gửi</h3><p>Kiểm tra MSSV và lớp. Mỗi MSSV chỉ có một lượt đăng ký trong sự kiện. Suất được xác nhận khi hệ thống lưu thành công.</p></aside></div>}</>;}
